// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    Button: typeof import('./src/components/Button/index.vue')['default']
    LButton: typeof import('./src/components/LButton/index.vue')['default']
  }
}
