// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    copy: typeof import('./src/components/LModal copy/index.vue')['default']
    LButton: typeof import('./src/components/LButton/index.vue')['default']
    LMessage: typeof import('./src/components/LMessage/index.vue')['default']
    LModal: typeof import('./src/components/LModal/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
